version: "3.7"
services:
  loadbalancer:
    image: httpd:2.4.54-bullseye
    ports:
      - "8080:80"
    volumes:
      - ./loadbalancer/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - "app"

  app:
    build: frontend/
    deploy:
      mode: replicated
      replicas: 2

  backend:
    build: backend/
    restart: on-failure
    ports:
      - "6868:8080"
    depends_on:
      - postgres
    env_file: ./.env
    environment:
      - spring.datasource.url="jdbc:postgresql://postgres:3306/5432?useSSL=false",
      - spring.datasource.password="$POSTGRES_PASSWORD",
      - spring.jpa.hibernate.ddl-auto="update",
      - spring.jpa.show-sql="true"

  postgres:
    image: postgres:15.0-bullseye
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
    ports:
      - "5454:5432"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
