version: "3.7"
services:
  loadbalancer:
    image: httpd:2.4.54-bullseye
    ports:
      - "8080:80"
    volumes:
      - ./loadbalancer/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - "app"

  app:
    build: frontend/
    deploy:
      mode: replicated
      replicas: 2

  backend:
    build: backend/
    restart: on-failure
    ports:
      - "6868:8080"
    depends_on:
      - "db"
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE

  db:
    image: postgres:15.0-bullseye
    restart: unless-stopped
    ports:
      - "8181:5432"
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    ports:
      - "8282:8080"
    depends_on:
      - "keycloakdb"
    env_file: ./.env
    environment:
      - KEYCLOAK_USER=$KEYCLOAK_ADMIN
      - KEYCLOAK_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
      - DB_VENDOR=$KC_DB
      - DB_ADDR=$KC_HOSTNAME
      - DB_PORT=$KC_PORT
      - DB_USER=$KC_DB_USERNAME
      - DB_PASSWORD=$KC_DB_PASSWORD
      - DB_DATABASE=$KC_DB
      - POSTGRES_USER=$KC_DB_USERNAME
      - POSTGRES_PASSWORD=$KC_DB_PASSWORD
      - POSTGRES_DATABASE=$KC_DB_SCHEMA
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/data/import/socialnetwork.json
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./keycloak/socialnetwork.json:/opt/jboss/keycloak/data/import/socialnetwork.json

  keycloakdb:
    image: postgres:15.0-bullseye
    env_file: ./.env
    environment:
      - POSTGRES_USER=$KC_DB_USERNAME
      - POSTGRES_PASSWORD=$KC_DB_PASSWORD
      - POSTGRES_DATABASE=$KC_DB_SCHEMA
