name: Build & Push Docker Frontend image

on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: registry.kthcloud.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build frontend/ --tag registry.kthcloud.com/data-ht2022/data10-frontend:${{ github.sha }}
    - name: Push the Docker image
      run: docker push registry.kthcloud.com/data-ht2022/data10-frontend:${{ github.sha }}
  
